import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import WelcomeModal from "@/components/modals/WelcomeModal";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["900"], // Black weight
  style: ["italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased overflow-x-hidden`}>
        {/* Header */}
        <Header />

        {/* Main content */}
        <main className="animate-fade-in flex min-h-screen flex-col bg-background font-sans">
          {children}
        </main>

        {/* Footer */}
        <Footer />

        {/* Welcome Modal */}
        <WelcomeModal />
      </body>
    </html>
  );
}
